apiVersion: v1
kind: ConfigMap
metadata:
  name: bittorrent-nginx-configmap
data:
  nginx.conf: |  
    events {}
    http {
      server {
        listen 80 ssl;  

        ssl_certificate /config/keys/fullchain.pem;
        ssl_certificate_key /config/keys/privkey.pem;

        location / {
          proxy_pass http://transmission-service:9091; 
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
