apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittorrent-nginx
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: bittorrent-nginx
  template:  
    metadata:
      labels:
        app: bittorrent-nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: obsidiana
      containers:
        - name: bittorrent-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf 
              subPath: nginx.conf 
            - name: ssl-certs
              mountPath: /config/keys 
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-config
          configMap:
            name: bittorrent-nginx-configmap 
        - name: ssl-certs
          hostPath: 
            path: /srv/bittorrent/nginx/keys
        - name: nginx-logs
          hostPath:
            path: /srv/bittorrent/nginx/log
