apiVersion: v1
kind: Service
metadata:
  name: bittorrent-nginx-service
spec:
  type: NodePort
  selector:
    app: bittorrent-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30666
      protocol: TCP
